apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-210523/pipeline:29dedb2ff19a5e86cf2a87506bbd0e29970be3a8
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
