apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-210523/pipeline:affed317a89567b61d52b000433162cb068a5633
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
